apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: APP-NAME
  labels:
    run: APP-NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: APP-NAME
    spec:
      containers:
      - name: APP-NAME
        image: DOCKER-IMAGE:latest
        imagePullPolicy: Always
        env:
        - name: EVENTHUBCONNSTRING
          value: "ENDPOINT-URL"
        - name: EVENTHUBPATH
          value: "EVENTHUB-PATH"
        - name: TEAMNAME
          value: "TEAM-NAME"
        - name: PROCESSENDPOINT
          value: "PROCESS-ENDPOINT"
        - name: PARTITIONKEY
          value: "1"
